Elektrodistribucija.Web/Areas/ServiserModul/Controllers/PrijavaKvaraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Elektrodistribucija.Data.DAL;
using Elektrodistribucija.Data.Models;
using Elektrodistribucija.Web.Areas.AdministratorModul.ViewModels;
using Elektrodistribucija.Web.Areas.ServiserModul.Models;
using Elektrodistribucija.Web.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Elektrodistribucija.Web.Areas.ServiserModul.Controllers
{
    [Autorizacija(administrator: true, ReferentKlijenti: false, Serviser: true)]
    [Area("ServiserModul")]
    public class PrijavaKvaraController : Controller
    {
        private MojContext _context;
        public PrijavaKvaraController(MojContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Dodaj()
        {
            PrijavaKvaraVM model = new PrijavaKvaraVM();

            ViewData["tipkvara"] = _context.TipKvara.ToList();
            ViewData["prikljucak"] = _context.Prikljucak.ToList();
            return View("Dodaj", model);
        }
        public IActionResult Snimi(PrijavaKvaraVM prijavaKvaraVM)
        {
            if (!ModelState.IsValid)
            {
                ViewData["tipkvara"] = _context.TipKvara.ToList();
                ViewData["prikljucak"] = _context.Prikljucak.ToList();
                return View("Dodaj", prijavaKvaraVM);
            }
            PrijavaKvara o = new PrijavaKvara();
            o.Opis = prijavaKvaraVM.Opis;
            o.Prikljucak = prijavaKvaraVM.Prikljucak;
            o.PrikljucakID = prijavaKvaraVM.PrikljucakID;
            o.Status = prijavaKvaraVM.Status;
            o.TipKvara = prijavaKvaraVM.TipKvara;
            o.TipKvaraID = prijavaKvaraVM.TipKvaraID;
            _context.PrijavaKvara.Add(o);
            _context.SaveChanges();

            return RedirectToAction("Dodaj");
        }
        public IActionResult Prikazi()
        {
            List<PrijavaKvara> prijavaKvaras = _context.PrijavaKvara.Include(x => x.TipKvara).ToList();
            prijavaKvaras = _context.PrijavaKvara.Include(x => x.Prikljucak).ToList();

            return View("Prikazi", prijavaKvaras);
        }

        public IActionResult Obrisi(int id)
        {
            _context.PrijavaKvara.Remove(_context.PrijavaKvara.FirstOrDefault(x => x.Id == id));
            _context.SaveChanges();

            return RedirectToAction("Prikazi");
        }
    }
}

Elektrodistribucija.Web/Areas/ServiserModul/Views/PrijavaKvara/Dodaj.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@using Elektrodistribucija.Web.Areas.ServiserModul.Models
@using Elektrodistribucija.Data.Models
@{
    ViewData["Title"] = "Dodaj";
    Layout = "~/Views/Shared/_LayoutServiser.cshtml";
    List<TipKvara> tipKvaras = (List<TipKvara>)ViewData["tipkvara"];
    List<Prikljucak> prikljucaks = (List<Prikljucak>)ViewData["prikljucak"];
}
@model PrijavaKvaraVM
<h2>Dodaj</h2>
<div class="container">
    <form asp-action="Snimi" asp-controller="PrijavaKvara">
        <div class="form-group">
            <label>Opis prijave kvara:</label>
            <input asp-for="Opis" class="form-control" />
            <span asp-validation-for="Opis" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Datum prijave:</label>
            <input asp-for="Datum" class="form-control" />
            <span asp-validation-for="Datum" class="text-danger"></span>
        </div>
        <div class="form-group">

            <select asp-for="TipKvaraID" class="form-control">
                <option>Odaberite tip kvara</option>
                @foreach (TipKvara d in tipKvaras)
                {
                    <option value="@d.Id">@d.Naziv</option>

                }
            </select>
            <span asp-validation-for="TipKvaraID" class="text-danger"></span>
        </div
        <div class="form-group">

            <select asp-for="PrikljucakID" class="form-control">
                <option>Odaberite prikljucak</option>
                @foreach (Prikljucak d in prikljucaks)
                {
                    <option value="@d.Id">@d.Adresa</option>

                }
            </select>
            <span asp-validation-for="PrikljucakID" class="text-danger"></span>
        </div>
        <input class="btn btn-primary btn-block" type="submit" value="Snimi" />
    </form>
</div>

Elektrodistribucija.Web/Areas/ServiserModul/Views/PrijavaKvara/Izmjeni.cshtml
@using Elektrodistribucija.Data.Models
@using Elektrodistribucija.Web.Areas.ServiserModul.Models
@{
    ViewData["Title"] = "Izmjeni";
    Layout = "~/Views/Shared/_LayoutServiser.cshtml";
}
@model PrijavaKvara
<h2>Izmjeni</h2>
<div class="container">
    <form asp-action="SnimiIzmjene" asp-contrller="TipKvaraController">
        <div class="form-group">
            <label>Opis</label>
            <input asp-for="Opis" class="form-control" />
            <span asp-validation-for="Opis" class="text-danger"></span>
            <input asp-for="Id" type="hidden" />
        </div>

        <div class="form-group">
            <label>Naziv</label>
            <input asp-for="TipKvara" class="form-control" />
            <span asp-validation-for="TipKvara" class="text-danger"></span>
            <input asp-for="Id" type="hidden" />
        </div>
        <input class="btn btn-primary btn-block" type="submit" value="Snimi" />
    </form>
</div>

Elektrodistribucija.Web/Areas/ServiserModul/Views/PrijavaKvara/Prikazi.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@using Elektrodistribucija.Web.Areas.ServiserModul.Models
@using Elektrodistribucija.Data.Models

@{
    ViewData["Title"] = "Prikazi";
    Layout = "~/Views/Shared/_LayoutServiser.cshtml";


}
@model List<PrijavaKvara>

<h2>Prijava Kvara</h2>
<table class="table">
    <thead>
        <tr>
            <th>Opis prijave kvara</th>
            <th>Tip Kvara</th>
            <th>Adresa prikljucka</th>
            <th>Datum prijave</th>

        </tr>
    </thead>
    <tbody>
        @foreach (PrijavaKvara k in Model)
        {
        <tr>
            <td>@k.Opis</td>
            <td>@k.TipKvara.Naziv</td>
            <td>@k.Prikljucak.Adresa</td>
            <td>@k.Datum</td>
            <td> <a id="obrisi" href="Obrisi?id=@k.Id" class="btn btn-danger">Obriši</a> </td>
            <td> <a id="Izmjeni" href="Izmjeni?id=@k.Id" class="btn btn-danger">Izmjeni</a> </td>
        </tr>

        }
    </tbody>
</table>