Elektrodistribucija.Web/Areas/ServiserModul/Controllers/OpremaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Elektrodistribucija.Data.DAL;
using Elektrodistribucija.Data.Models;
using Elektrodistribucija.Web.Areas.AdministratorModul.ViewModels;
using Elektrodistribucija.Web.Areas.ServiserModul.Models;
using Elektrodistribucija.Web.Helper;
using Microsoft.AspNetCore.Mvc;

namespace Elektrodistribucija.Web.Areas.ServiserModul.Controllers
{
    [Autorizacija(administrator: true, ReferentKlijenti: false,  Serviser: true)]
    [Area("ServiserModul")]
    public class OpremaController : Controller
    {
        private MojContext _context;
        public OpremaController(MojContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Dodaj()
        {
            return View("Dodaj");
        }
        public IActionResult Snimi(OpremaVM oprema)
        {
            if (ModelState.IsValid)
            {


                Oprema o = new Oprema();
                o.Naziv = oprema.Naziv;

                _context.Oprema.Add(o);
                _context.SaveChanges();

                return RedirectToAction("Dodaj");
            }
            return View("Dodaj",oprema);
        }
        public IActionResult Prikazi()
        {
            List<Oprema> oprema = _context.Oprema.ToList();

            return View("Prikazi",oprema);
        }

        public IActionResult Obrisi(int id)
        {
            if (_context.Oprema.SingleOrDefault(x => x.Id == id) != null)
            { 
            _context.Oprema.Remove(_context.Oprema.FirstOrDefault(x => x.Id == id));

                _context.SaveChanges();

                return RedirectToAction("Prikazi");
            }

            return View("Prikazi");
        }

        public IActionResult Izmjeni(int id)
        {
           
            Oprema opr=_context.Oprema.SingleOrDefault(x => x.Id == id);

            return View("Izmjeni",opr);
        }

        public IActionResult SnimiIzmjene(Oprema oprema)
        {

            _context.Oprema.Update(oprema);
            _context.SaveChanges();

            return RedirectToAction("Prikazi");
        }


    }
}

Elektrodistribucija.Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Elektrodistribucija.Data.DAL;
using Elektrodistribucija.Data.EntityModels;
using Elektrodistribucija.Data.Models;
using Elektrodistribucija.Web.Helper;
using Elektrodistribucija.Web.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Elektrodistribucija.Web.Controllers
{
    public class LoginController : Controller
    {
        private MojContext _context;
        public LoginController(MojContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(new LoginVM()
            {
                zapamtiPassword = true,
            });

        }

        public IActionResult Login(LoginVM input)
        {
            KorisnickiNalog korisnickiNalog = _context.KorisnickiNalog.SingleOrDefault(x => x.KorisnickoIme == input.KorisnickoIme && x.Lozinka == input.Lozinka);




            if (korisnickiNalog == null)
            {
                TempData["error_poruka"] = "Pogrešni podatci za login";

               return View("Index", input);
            }

            HttpContext.SetLogiraniKorisnik(korisnickiNalog, input.zapamtiPassword);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Logout()
        {
         

            
            
            return RedirectToAction("Index");
            
        }
    }
}

Elektrodistribucija.Web/Controllers/SesijeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Elektrodistribucija.Data.DAL;
using Elektrodistribucija.Data.Models;
using Elektrodistribucija.Web.Helper;
using Elektrodistribucija.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Elektrodistribucija.Web.Controllers
{
    [Autorizacija(administrator:true,ReferentKlijenti:true,Serviser:true)]
    public class SesijeController : Controller
    {
        private MojContext _context;
        public SesijeController(MojContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            SesijaIndexVM model = new SesijaIndexVM();
            model.Rows = _context.AutorizacijaToken.Select(x => new SesijaIndexVM.Row
            {
                VrijemeLogiranja = x.VrijemeEvidentiranja,
                token = x.Vrijednost,
                IPAdresa = x.IpAdresa

            }).ToList();

            model.TrenutniToken = HttpContext.GetTrenutniToken();
            KorisnickiNalog korisnik = Autentifikacija.GetLogiraniKorisnik(HttpContext);
           
            ViewData["permisija"] = _context.Uloge.FirstOrDefault(x => x.Id == korisnik.UlogaID).NazivUloge.ToString();

            return View(model);
        }
        public IActionResult Obrisi(string token)
        {
            var obrisati = _context.AutorizacijaToken.FirstOrDefault(x => x.Vrijednost == token);
            if(obrisati!=null)
            {
                _context.AutorizacijaToken.Remove(obrisati);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Elektrodistribucija.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Elektrodistribucija.Data.Models
@using Elektrodistribucija.Web.Helper
@{ 
    KorisnickiNalog korisnik = Context.GetLogiraniKorisnik();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Elektrodistribucija</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Elektrodistribucija.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Početna</a></li>
                    
                    <li><a asp-area="" asp-controller="Sesije" asp-action="Index">Sesije</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Logout">
                        @if(korisnik !=null)
                        {
                            <label>
                                @korisnik.KorisnickoIme
                                Odjava
                            </label>

                        }
                        else
                        {
                            <label>Prijava</label>

                        }
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Elektrodistribucija.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Elektrodistribucija.Web/Views/Shared/_LayoutAdministrator.cshtml
@using Microsoft.AspNetCore.Http
@using Elektrodistribucija.Data.Models
@using Elektrodistribucija.Web.Helper
@{ 
    KorisnickiNalog korisnik = Context.GetLogiraniKorisnik();
   
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Elektrodistribucija</title>

    <environment include="Development">

    </environment>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    @*<script src="/js/site.js"></script>*@
    <script src="~/jsFIT.js"></script>
</head>
<body>


    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="AdministratorModul" asp-controller="AdministratorHome" asp-action="Index">Početna</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Korisnici <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="AdministratorModul" asp-controller="Korisnici" asp-action="Dodaj">Dodaj korisnika</a></li>
                            <li><a asp-area="AdministratorModul" asp-controller="Korisnici" asp-action="Prikazi">Prikaži korisnike</a></li>


                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Direkcije <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="AdministratorModul" asp-controller="Direkcije" asp-action="Dodaj">Dodaj direkciju</a></li>
                            <li><a asp-area="AdministratorModul" asp-controller="Direkcije" asp-action="Prikazi">Prikazi direkcije</a></li>


                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Odjeli <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="AdministratorModul" asp-controller="Odjel" asp-action="Dodaj">Dodaj odjel</a></li>
                            <li><a asp-area="AdministratorModul" asp-controller="Odjel" asp-action="Prikazi">Prikazi odjele</a></li>


                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Sesije" asp-action="Index">Sesije</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li> <a>Dobro došli @korisnik.KorisnickoIme </a></li>
                    <li>

                        <a asp-area="" asp-controller="Login" asp-action="Logout">
                            Odjava
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Elektrodistribucija</p>
        </footer>
    </div>

    

    @RenderSection("Scripts", required: false)
</body>
</html>

Elektrodistribucija.Web/Views/Shared/_LayoutAnonimus.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Elektrodistribucija.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
   
    <div class="container body-content">
        @RenderBody()
       
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Elektrodistribucija.Web/Views/Shared/_LayoutReferentZaKlijente.cshtml
@using Microsoft.AspNetCore.Http
@using Elektrodistribucija.Data.Models
@using Elektrodistribucija.Web.Helper
@{ 
    KorisnickiNalog korisnik = Context.GetLogiraniKorisnik();
   
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Elektrodistribucija</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>

    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    <script src="/js/site.js"></script>

    <script src="/jsFIT.js"></script>
</head>
<body>
   

    <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="ReferentZaklijenteModul" asp-controller="ReferentZaklijenteHome" asp-action="Index">Početna</a></li>
                        <li><a asp-area="ReferentZaklijenteModul" asp-controller="Cijena" asp-action="Cijena">Cijena struje</a></li>


                       
                        <li><a asp-area="" asp-controller="Sesije" asp-action="Index">Sesije</a></li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li> <a>Dobro došli @korisnik.KorisnickoIme </a></li>
                        <li>

                            <a asp-area="" asp-controller="Login" asp-action="Logout">
                                Odjava
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Elektrodistribucija</p>
        </footer>
    </div>

    

    @RenderSection("Scripts", required: false)
</body>
</html>

Elektrodistribucija.Web/Views/Shared/_LayoutServiser.cshtml
@using Microsoft.AspNetCore.Http
@using Elektrodistribucija.Data.Models
@using Elektrodistribucija.Web.Helper
@{ 
    KorisnickiNalog korisnik = Context.GetLogiraniKorisnik();
   
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Elektrodistribucija</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    <script src="/js/site.js"></script>

    <script src="/jsFIT.js"></script>

</head>
<body>
   

    <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="ServiserModul" asp-controller="ServiserHome" asp-action="Index">Početna</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Oprema <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="ServiserModul" asp-controller="Oprema" asp-action="Dodaj">Dodaj opremu</a></li>
                                <li><a asp-area="ServiserModul" asp-controller="Oprema" asp-action="Prikazi">Prikaži opremu</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tip kvara <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="ServiserModul" asp-controller="TipKvara" asp-action="Dodaj">Dodaj tip kvara</a></li>
                                <li><a asp-area="ServiserModul" asp-controller="TipKvara" asp-action="Prikazi">Prikaži tip kvara</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Prijava kvara <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="ServiserModul" asp-controller="PrijavaKvara" asp-action="Dodaj">Dodaj novu prijavu kvara</a></li>
                                <li><a asp-area="ServiserModul" asp-controller="PrijavaKvara" asp-action="Prikazi">Prikaži sve prijave kvarova</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Intervencija <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="ServiserModul" asp-controller="Intervencija" asp-action="Dodaj">Dodaj novu intervenciju </a></li>
                                <li><a asp-area="ServiserModul" asp-controller="Intervencija" asp-action="Prikazi">Prikaži sve intervencije</a></li>
                            </ul>
                        </li>
                        <li><a asp-area="" asp-controller="Sesije" asp-action="Index">Sesije</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li> <a>Dobro došli @korisnik.KorisnickoIme </a></li>
                        <li>

                            <a asp-area="" asp-controller="Login" asp-action="Logout">
                                Odjava
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Elektrodistribucija</p>
        </footer>
    </div>

    

    @RenderSection("Scripts", required: false)
</body>
</html>