Elektrodistribucija.Web/Areas/AdministratorModul/Controllers/KorisniciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Elektrodistribucija.Data.DAL;
using Elektrodistribucija.Data.Models;
using Elektrodistribucija.Web.Areas.AdministratorModul.ViewModels;
using Elektrodistribucija.Web.Helper;
using Elektrodistribucija.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Elektrodistribucija.Web.Areas.AdministratorModul.Controllers
{
    [Autorizacija(administrator: true, ReferentKlijenti: false,  Serviser: false)]
    [Area("AdministratorModul")]
    public class KorisniciController : Controller
    {
        private MojContext _context;
        

        

        public KorisniciController(MojContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Dodaj()
        {
            KorisniciDodajVM korisnici = new KorisniciDodajVM();
            korisnici.uloge = new List<Uloge>();
           
            List<Uloge> uloge = _context.Uloge.ToList();

            foreach(Uloge u in uloge)
            {

                korisnici.uloge.Add(u);
            }


            return View("Dodaj",korisnici);
        }
        public IActionResult Snimi(KorisniciDodajVM korisnik)
        {
            if (!ModelState.IsValid)
            {
                KorisniciDodajVM korisnici = new KorisniciDodajVM();
                korisnici.uloge = new List<Uloge>();

                List<Uloge> uloge = _context.Uloge.ToList();

                foreach (Uloge u in uloge)
                {

                    korisnici.uloge.Add(u);
                }
                return View("Dodaj", korisnici);
            }



            Uloge uloga = _context.Uloge.FirstOrDefault(x => x.Id == korisnik.UlogaId);

            if(uloga.NazivUloge=="Administrator")
            {
                Administrator administrator = new Administrator
                {
                    Ime = korisnik.Ime,
                    Prezime = korisnik.Prezime,
                    Telefon = korisnik.Telefon,
                    JMBG = korisnik.JMBG,
                    Adresa = korisnik.Adresa,
                    KorisnickiNalog = new KorisnickiNalog
                    {
                        KorisnickoIme = korisnik.KorisnickoIme,
                        Lozinka = korisnik.Lozinka,
                        UlogaID = korisnik.UlogaId
                    }
                };

                _context.Administrator.Add(administrator);
                _context.SaveChanges();
                return RedirectToAction("Prikazi");
            }

            if(uloga.NazivUloge== "Referent za klijente")
            {
                ReferentKlijenti Rklijenti = new ReferentKlijenti
                {
                    Ime = korisnik.Ime,
                    Prezime = korisnik.Prezime,
                    Telefon = korisnik.Telefon,
                    JMBG = korisnik.JMBG,
                    Adresa = korisnik.Adresa,
                    KorisnickiNalog = new KorisnickiNalog
                    {
                        KorisnickoIme = korisnik.KorisnickoIme,
                        Lozinka = korisnik.Lozinka,
                        UlogaID = korisnik.UlogaId
                    }
                };
                _context.ReferentKlijenti.Add(Rklijenti);
                _context.SaveChanges();
                return RedirectToAction("Prikazi");
            }

           


            if (uloga.NazivUloge == "Serviser")
            {
               Serviser serviser = new Serviser
                {
                    Ime = korisnik.Ime,
                    Prezime = korisnik.Prezime,
                    Telefon = korisnik.Telefon,
                    JMBG = korisnik.JMBG,
                    Adresa = korisnik.Adresa,
                    KorisnickiNalog = new KorisnickiNalog
                    {
                        KorisnickoIme = korisnik.KorisnickoIme,
                        Lozinka = korisnik.Lozinka,
                        UlogaID = korisnik.UlogaId
                    }
                };
                _context.Serviser.Add(serviser);
                _context.SaveChanges();
                return RedirectToAction("Prikazi");
            }


            return RedirectToAction("Prikazi");







        }

        public IActionResult Prikazi()
        {

           List<KorisniciPrikaziVM> korisnici = new List<KorisniciPrikaziVM>();

            List<Administrator> administratori = _context.Administrator.Include(x => x.KorisnickiNalog).ThenInclude(y => y.Uloga).ToList();
            List<ReferentKlijenti> referentZaklijente = _context.ReferentKlijenti.Include(x => x.KorisnickiNalog).ThenInclude(y => y.Uloga).ToList();
            List<Serviser> serviser = _context.Serviser.Include(x => x.KorisnickiNalog).ThenInclude(y => y.Uloga).ToList();

           
            foreach(Administrator a in administratori)
            {
                KorisniciPrikaziVM k = new KorisniciPrikaziVM
                {
                    
                    Ime = a.Ime,
                    Prezime = a.Prezime,
                    KorisnickoIme = a.KorisnickiNalog.KorisnickoIme,
                    Lozinka = a.KorisnickiNalog.Lozinka,
                    Telefon = a.Telefon,
                    JMBG = a.JMBG,
                    Adresa = a.Adresa,
                    Uloga = a.KorisnickiNalog.Uloga.NazivUloge,
                    KorisniciPrikaziID=Convert.ToInt32(a.KorisnickiNalogId)
                };

                korisnici.Add(k);
               
            }

            foreach (ReferentKlijenti a in referentZaklijente)
            {
                KorisniciPrikaziVM k = new KorisniciPrikaziVM
                {
                    Ime = a.Ime,
                    Prezime = a.Prezime,
                    KorisnickoIme = a.KorisnickiNalog.KorisnickoIme,
                    Lozinka = a.KorisnickiNalog.Lozinka,
                    Telefon = a.Telefon,
                    JMBG = a.JMBG,
                    Adresa = a.Adresa,
                    Uloga = a.KorisnickiNalog.Uloga.NazivUloge,
                    KorisniciPrikaziID = Convert.ToInt32(a.KorisnickiNalogId)
                };

                korisnici.Add(k);

            }

           
            foreach (Serviser a in serviser)
            {
                KorisniciPrikaziVM k = new KorisniciPrikaziVM
                {
                    Ime = a.Ime,
                    Prezime = a.Prezime,
                    KorisnickoIme = a.KorisnickiNalog.KorisnickoIme,
                    Lozinka = a.KorisnickiNalog.Lozinka,
                    Telefon = a.Telefon,
                    JMBG = a.JMBG,
                    Adresa = a.Adresa,
                    Uloga = a.KorisnickiNalog.Uloga.NazivUloge,
                    KorisniciPrikaziID = Convert.ToInt32(a.KorisnickiNalogId)
                };

                korisnici.Add(k);

            }




            return View("Prikazi",korisnici);
        }

        
        public IActionResult Obrisi(int id)
        {
            
            if(_context.Administrator.SingleOrDefault(x=>x.KorisnickiNalogId==id)!=null)
            {
                _context.Administrator.Remove(_context.Administrator.FirstOrDefault(x => x.KorisnickiNalogId == id));
                _context.KorisnickiNalog.Remove(_context.KorisnickiNalog.FirstOrDefault(x => x.Id == id));
                _context.SaveChanges();
               
                return RedirectToAction("Prikazi");
            }

            if (_context.ReferentKlijenti.SingleOrDefault(x => x.KorisnickiNalogId == id) != null)
            {
                _context.ReferentKlijenti.Remove(_context.ReferentKlijenti.FirstOrDefault(x => x.KorisnickiNalogId == id));
                _context.KorisnickiNalog.Remove(_context.KorisnickiNalog.FirstOrDefault(x => x.Id == id));
                _context.SaveChanges();
                return RedirectToAction("Prikazi");
            }

           

            if (_context.Serviser.SingleOrDefault(x => x.KorisnickiNalogId == id) != null)
            {
                _context.Serviser.Remove(_context.Serviser.FirstOrDefault(x => x.KorisnickiNalogId == id));
                _context.KorisnickiNalog.Remove(_context.KorisnickiNalog.FirstOrDefault(x => x.Id == id));
                _context.SaveChanges();
                return RedirectToAction("Prikazi");
            }
            return RedirectToAction("Prikazi");
        }
        public IActionResult Izmjeni(int id)
        {

            KorisnickiNalog nalog = _context.KorisnickiNalog.FirstOrDefault(x => x.Id == id);
            KorisniciDodajVM korisn = new KorisniciDodajVM();
            Uloge u = _context.Uloge.FirstOrDefault(x => x.Id == nalog.UlogaID);
          if (u.NazivUloge=="Administrator")
            {
                Administrator a = _context.Administrator.SingleOrDefault(x => x.KorisnickiNalogId == nalog.Id);


               korisn.Ime = a.Ime;
                korisn.Prezime = a.Prezime;
               korisn.Telefon = a.Telefon;
               korisn.JMBG = a.JMBG;
               korisn.Adresa = a.Adresa;
               korisn.KorisnickoIme = nalog.KorisnickoIme;
               korisn.Lozinka = nalog.Lozinka;
               korisn.UlogaId = Convert.ToInt32(nalog.UlogaID);
                

                korisn.uloge = new List<Uloge>();
                List<Uloge> ulog = _context.Uloge.ToList();

                foreach (Uloge ulo in ulog)
                {

                    korisn.uloge.Add(ulo);
                }
                
            }
            if (u.NazivUloge == "Referent za klijente")
            {
                ReferentKlijenti a = _context.ReferentKlijenti.SingleOrDefault(x => x.KorisnickiNalogId == nalog.Id);


                korisn.Ime = a.Ime;
                korisn.Prezime = a.Prezime;
                korisn.Telefon = a.Telefon;

Elektrodistribucija.Web/Areas/AdministratorModul/Views/Korisnici/Dodaj.cshtml
@using Elektrodistribucija.Data.Models
@using Elektrodistribucija.Web.Areas.AdministratorModul.ViewModels

@model KorisniciDodajVM
@{

    ViewData["Title"] = "Dodaj";
    Layout = "~/Views/Shared/_LayoutAdministrator.cshtml";
    string error_imaUser = (string)TempData["user"];

}




<h2>Dodaj korisnika</h2>
<div class="container">
    <form asp-action="Snimi" asp-controller="Korisnici">
        <div class="row ">
            <div class="col col-lg-6">
                @if (error_imaUser != null)
            {

                <br />
                <div class="alert alert-danger">

                    @error_imaUser
                </div>


        }

                <div class="form-group">
                    <label> Ime</label>
                    <div>

                        <input asp-for="Ime" class="form-control" />
                        <span asp-validation-for="Ime" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label> Prezime</label>
                    <div>
                        <input asp-for="Prezime" class="form-control" />
                        <span asp-validation-for="Prezime" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label> Telefon</label>
                    <div>
                        <input asp-for="Telefon" type="tel" class="form-control" />
                        <span asp-validation-for="Telefon" class="text-danger"></span>
                    </div>
                </div>


                <div class="form-group">
                    <label> JMBG</label>
                    <div>
                        <input asp-for="JMBG" type="number" class="form-control" />
                        <span asp-validation-for="JMBG" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label> Adresa</label>
                    <div>
                        <input asp-for="Adresa" class="form-control" />
                        <span asp-validation-for="Adresa" class="text-danger"></span>
                    </div>
                </div>


            </div>
            <div class="col col-lg-6">
                <div class="form-group">
                    <label> Korisnicko ime</label>
                    <div>
                        <input asp-for="KorisnickoIme" class="form-control" />
                        <span asp-validation-for="KorisnickoIme" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label> Lozinka</label>
                    <div>
                        <input asp-for="Lozinka" type="password" class="form-control" />
                        <span asp-validation-for="Lozinka" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label>Tip korisnika</label>
                    <select asp-for="UlogaId" class="form-control">
                        <option>Odaberite tip korisnika</option>
                        @foreach (Uloge k in Model.uloge)
                    {
                        <option value="@k.Id">@k.NazivUloge</option>

                }


                    </select>
                    <span asp-validation-for="UlogaId" class="text-danger"></span>

                </div>
            </div>





        </div>
        <input class="btn btn-primary btn-block" type="submit" value="Snimi" />
    </form>
</div>

Elektrodistribucija.Web/Areas/AdministratorModul/Views/Korisnici/DodajPlatu.cshtml
@model Elektrodistribucija.Web.Areas.AdministratorModul.ViewModels.PlataVM

  <h2>Trenutna plata </h2>
<form asp-action="SnimiPlatu" ajax-poziv="ne">
    <div class="row ">
        <div class="col col-lg-6">
            <div class="form-group">
                <label asp-for="Osnova">Osnovica</label>
                <input asp-for="Osnova" value="@Model.Osnova" class="form-control" />
                <span asp-validation-for="Osnova" class="text-danger">
                </span>
            </div>
            <div class="form-group">
                <label asp-for="Bonus">Bonus</label>
                <input asp-for="Bonus" value="@Model.Bonus" class="form-control" />
                <span asp-validation-for="Bonus" class="text-danger">
                </span>
            </div>
            <div class="form-group">
                <label >Ukupno</label>
                <input value="@Model.Ukupno" readonly class="form-control" />
               
            </div>

            <input asp-for="KorisnickiNalogID" value="@Model.KorisnickiNalogID" type="hidden" />
            <br />
            <input id="snimi" class=" btn btn-primary" type="submit" value="Snimi platu" />
        </div>
        </div>
</form>
<br />
<script>

</script>

Elektrodistribucija.Web/Areas/AdministratorModul/Views/Korisnici/Izmjeni.cshtml
@using Elektrodistribucija.Web.Areas.AdministratorModul.ViewModels
@using Elektrodistribucija.Data.Models
@{
    ViewData["Title"] = "Izmjeni";
    Layout = "~/Views/Shared/_LayoutAdministrator.cshtml";
}
@model KorisniciDodajVM
<h2>Izmjeni korisnika </h2>

<div class="container">
    <form asp-action="Update" asp-controller="Korisnici">
        <div class="row ">
            <div class="col col-lg-6">
               

                <div class="form-group">
                    <label> Ime</label>
                    <div>

                        <input value="@Model.Ime" asp-for="Ime" class="form-control" />
                        <span asp-validation-for="Ime" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label> Prezime</label>
                    <div>
                        <input value="@Model.Prezime" asp-for="Prezime" class="form-control" />
                        <span asp-validation-for="Prezime" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label> Telefon</label>
                    <div>
                        <input value="@Model.Telefon" asp-for="Telefon" type="tel" class="form-control" />
                        <span asp-validation-for="Telefon" class="text-danger"></span>
                    </div>
                </div>


                <div class="form-group">
                    <label> JMBG</label>
                    <div>
                        <input value="@Model.JMBG" asp-for="JMBG" type="number" class="form-control" />
                        <span asp-validation-for="JMBG" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label> Adresa</label>
                    <div>
                        <input value="@Model.Adresa" asp-for="Adresa" class="form-control" />
                        <span asp-validation-for="Adresa" class="text-danger"></span>
                    </div>
                </div>


            </div>
            <div class="col col-lg-6">
                <div class="form-group">
                    <label> Korisnicko ime</label>
                    <div>
                        <input value="@Model.KorisnickoIme" readonly asp-for="KorisnickoIme" class="form-control" />
                        <span asp-validation-for="KorisnickoIme" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label> Lozinka</label>
                    <div>
                        <input value="@Model.Lozinka" asp-for="Lozinka" type="password" class="form-control" />
                        <span asp-validation-for="Lozinka" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label>Tip korisnika</label>
                    <select  asp-for="UlogaId" class="form-control">
                        <option>Odaberite tip korisnika</option>
                        @foreach (Uloge k in Model.uloge)
                        {
                            if (k.Id == Model.UlogaId)
                            {
                                <option selected value="@k.Id">@k.NazivUloge</option>

                            }
                            else
                            {
                            <option value="@k.Id">@k.NazivUloge</option>
                            }
                        }


                    </select>
                    <span asp-validation-for="UlogaId" class="text-danger"></span>

                </div>
            </div>





        </div>
        <input class="btn btn-primary btn-block" type="submit" value="Snimi" />
    </form>
    </div>

Elektrodistribucija.Web/Areas/AdministratorModul/Views/Korisnici/Prikazi.cshtml
@using Elektrodistribucija.Data.Models
@using System
@using System.Collections.Generic
@using Elektrodistribucija.Web.ViewModels
@using Elektrodistribucija.Web.Areas.AdministratorModul.ViewModels
@{
    ViewData["Title"] = "Prikazi";
   

    Layout = "~/Views/Shared/_LayoutAdministrator.cshtml";

}
@model List<KorisniciPrikaziVM>

<h2>Svi korisnici sistema elektrodistribucije</h2>



<table class="table">
    <thead>
        <tr>
          
            <th>Ime</th>
            <th>Prezime</th>
            <th>Adresa</th>
            <th>Telefon</th>
            <th>JMBG</th>
            <th>Tip korisnika</th>

        </tr>
    </thead>
    <tbody>
        @foreach (KorisniciPrikaziVM k in Model)
        {
        <tr>

            <td>@k.Ime</td>
            <td>@k.Prezime</td>
            <td>@k.Adresa</td>
            <td>@k.Telefon</td>
            <td>@k.JMBG</td>
            <td>@k.Uloga</td>

            <td>
                <a asp-action="DodajPlatu" ajax-poziv="da" ajax-rezultat="DodajDiv" asp-route-korisniciNalogID="@k.KorisniciPrikaziID"  class="btn btn-primary">Plata</a>
            </td>
            <td> <a id="obrisi" href="Obrisi?id=@k.KorisniciPrikaziID" class="btn btn-danger">Obriši</a> </td>
            <td> <a id="izmjeni" href="Izmjeni?id=@k.KorisniciPrikaziID" class="btn btn-danger">Izmjeni</a> </td>
        </tr>
        <tr>
            <div id="DodajDiv">

            </div>
        </tr>

        
            
        

        }
    </tbody>
</table>